/** @type {import('tailwindcss').Config} */
const defaultTheme = require("tailwindcss/defaultTheme");
export default {
    darkMode: "class",
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
    ],
    theme: {
        extend: {
            colors: {
                primary: {
                    50: "#eff6ff",
                    100: "#dbeafe",
                    200: "#bfdbfe",
                    300: "#93c5fd",
                    400: "#60a5fa",
                    500: "#3b82f6",
                    600: "#2563eb",
                    700: "#1d4ed8",
                    800: "#1e40af",
                    900: "#1e3a8a",
                    950: "#172554",
                },
            },
            fontFamily: {
                sans: ["Inter", ...defaultTheme.fontFamily.sans],
                body: [
                    "Inter",
                    "ui-sans-serif",
                    "system-ui",
                    "-apple-system",
                    "system-ui",
                    "Segoe UI",
                    "Roboto",
                    "Helvetica Neue",
                    "Arial",
                    "Noto Sans",
                    "sans-serif",
                    "Apple Color Emoji",
                    "Segoe UI Emoji",
                    "Segoe UI Symbol",
                    "Noto Color Emoji",
                ],
            },
        },
    },
    plugins: [require("flowbite/plugin"), require("flowbite-typography")],
    safelist: [
        "bg-green-100",
        "bg-red-100",
        "bg-blue-100",
        "bg-yellow-100",
        "bg-gray-100",
        "bg-indigo-100",
        "bg-pink-100",
        "bg-cyan-100",
        "bg-teal-100",
        "bg-lime-100",
        "bg-amber-100",
        "bg-orange-100",
        "bg-rose-100",
        "bg-sky-100",
        "bg-fuchsia-100",
        "bg-violet-100",
        "bg-emerald-100",
        "bg-slate-100",
        "bg-zinc-100",
        "bg-stone-100",
        "bg-green-500",
        "bg-red-500",
        "bg-blue-500",
        "bg-yellow-500",
        "bg-gray-500",
        "bg-indigo-500",
        "bg-pink-500",
        "bg-cyan-500",
        "bg-teal-500",
        "bg-lime-500",
        "bg-amber-500",
        "bg-orange-500",
        "bg-rose-500",
        "bg-sky-500",
        "bg-fuchsia-500",
        "bg-violet-500",
        "bg-emerald-500",
        "bg-slate-500",
        "bg-zinc-500",
        "bg-stone-500",
        "text-green-500",
        "text-red-500",
        "text-green-700",
        "text-red-700",
    ],
};
